# Generated by Django 6.1.1 on 2026-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_id', models.CharField(max_length=30, unique=True)),
                ('domain', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('provision', models.TextField()),
                ('source_title', models.CharField(max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('clause_type', models.CharField(choices=[('deterministic', 'Deterministic'), ('explanatory', 'Explanatory'), ('procedural', 'Procedural')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=30, unique=True)),
                ('domain', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('clause_ids', models.JSONField(blank=True, default=list)),
                ('stop_processing', models.BooleanField(default=False)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
